<a href="https://colab.research.google.com/github/Wivieto177/ai202402/blob/main/Practica_numpy_Martes_29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Library

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [ ]:
print(type(myArray))

<class 'numpy.ndarray'>


In [ ]:
print(myArray.shape)
print(myArray[3])
myArray[2]=28
print(myArray)

(5,)
4
[ 1  2 28  4  5]


In [ ]:
myArray2=np.array([[1,2,3],[4,5,6]])
print(myArray2)
print(myArray2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
myArray3=np.zeros([5,5])
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
myArray4=np.full([3,6], 10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones([5,5])
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
myArray7=np.random.random([5,5])
print(myArray7)


[[0.20810716 0.69913849 0.73014688 0.14915803 0.88659894]
 [0.76798212 0.32934119 0.04403598 0.81397568 0.71429562]
 [0.60330224 0.73290446 0.76058668 0.349051   0.14355412]
 [0.25601432 0.86070987 0.75218631 0.81613484 0.07514359]
 [0.5904549  0.21306065 0.48184404 0.72269196 0.5966606 ]]


In [ ]:
myArray8=np.random.randint(10, size=(5,5))
print(myArray8)

[[5 3 0 2 9]
 [9 1 7 6 0]
 [4 0 4 4 4]
 [6 2 2 8 6]
 [8 9 0 3 6]]


In [ ]:
myMatrix=myArray8[:2,:2]
print(myMatrix)

[[9 3]
 [9 9]]


In [ ]:
myArray8[2,2]=100
print(myArray8)

[[  5   3   0   2   9]
 [  9   1   7   6   0]
 [  4   0 100   4   4]
 [  6   2   2   8   6]
 [  8   9   0   3   6]]


In [ ]:
print(myArray8[:,2].shape)

(5,)


In [ ]:
myMatrix=myArray8[1:4,1:4]
print(myMatrix)

[[  1   7   6]
 [  0 100   4]
 [  2   2   8]]


In [ ]:
matrixA = np.array([[12,13,14,15],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)

(3, 4)


In [ ]:
matrixA

array([[12, 13, 14, 15],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [ ]:
# prompt: Crea una matriz aleatoria de 4x3 con numeros enteros

import numpy as np

# Crea una matriz aleatoria de 4x3 con números enteros entre 0 y 9
random_matrix = np.random.randint(10, size=(4, 3))

random_matrix

array([[5, 4, 8],
       [7, 2, 6],
       [5, 4, 7],
       [7, 8, 1]])

In [ ]:
print(random_matrix)
col_indice=np.array([0,1,2])
row_indice=np.array([1,2])
for row,col in zip(row_indice,col_indice):
  print(random_matrix[row,col])



[[5 4 8]
 [7 2 6]
 [5 4 7]
 [7 8 1]]
7
4


In [ ]:
mask=random_matrix>4
print(mask)

[[ True False  True]
 [ True False  True]
 [ True False  True]
 [ True  True False]]


In [ ]:
print(random_matrix[mask])

[5 8 7 6 5 7 7 8]


In [ ]:
print(random_matrix[random_matrix>7])

[8 8]


In [ ]:
print(random_matrix)

[[0.56041125 0.95128667]
 [0.2826931  0.81869334]]


In [ ]:
matrix11=np.random.rand(2,2)
print(matrix11)

[[0.69112138 0.26900443]
 [0.8210423  0.62852705]]


In [ ]:
random_matrix[(random_matrix>3) & (random_matrix<9)] += 100
print(random_matrix)

[[0.56041125 0.95128667]
 [0.2826931  0.81869334]]


In [ ]:
import numpy as np
random_matrix = np.random.randint(10, size=(4, 3))

random_matrix

array([[7, 4, 8],
       [6, 2, 7],
       [2, 9, 0],
       [7, 0, 8]])

In [ ]:
print(np.sqrt(random_matrix))

[[2.64575131 2.         2.82842712]
 [2.44948974 1.41421356 2.64575131]
 [1.41421356 3.         0.        ]
 [2.64575131 0.         2.82842712]]


In [ ]:
matrixA1 = np.random.randint(0, 10, size=(2, 5))
print(matrixA1)

[[0 1 9 9 9]
 [6 2 4 0 3]]


In [ ]:
print(np.mean(matrixA1))

4.3


In [ ]:
print(matrixA1.mean(axis=1))

[5.6 3. ]


In [ ]:
print(matrixA1.mean(axis=0))

[3.  1.5 6.5 4.5 6. ]


In [ ]:
print(matrixA1.max())

9


In [ ]:
print(matrixA1.min())

0


In [ ]:
print(matrixA1.sum())

43


In [ ]:
print(np.median(matrixA1))

3.5


In [ ]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
add_rows=np.array([1,0,2])
print(add_rows.shape)

(3,)


In [ ]:
y=start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [145]:
col_rows=np.array([[0,1,2,3]])
print(col_rows.shape)

(1, 4)


In [146]:
print(start)
tmp=col_rows.T
y2=start+tpm
print(y2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


NameError: name 'tpm' is not defined

In [151]:
tmp1=np.array([[1,1],[2,2]])
tmp2=np.array([[3,3],[4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [152]:
print(np.dot(tmp1,tmp2))

[[ 7  7]
 [14 14]]


In [153]:
y1=np.random.randint(low=2, high=50, size=(2,2))
y2=np.random.randint(low=2, high=50, size=(2,2))
print(y1)
print(y2)

[[27 31]
 [20 22]]
[[30 18]
 [42 42]]


In [155]:
np.vstack((y1,y2))

array([[27, 31],
       [20, 22],
       [30, 18],
       [42, 42]])

In [156]:
np.hstack((y1,y2))

array([[27, 31, 30, 18],
       [20, 22, 42, 42]])