<a href="https://colab.research.google.com/github/Wivieto177/ai202402/blob/main/Practica_numpy_Martes_29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Library

In [4]:
import numpy as np

In [6]:
print(np.__version__)

1.26.4


In [7]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [10]:
print(type(myArray))

<class 'numpy.ndarray'>


In [18]:
print(myArray.shape)
print(myArray[3])
myArray[2]=28
print(myArray)

(5,)
4
[ 1  2 28  4  5]


In [19]:
myArray2=np.array([[1,2,3],[4,5,6]])
print(myArray2)
print(myArray2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [21]:
myArray3=np.zeros([5,5])
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
myArray4=np.full([3,6], 10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones([5,5])
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
myArray7=np.random.random([5,5])
print(myArray7)


[[0.20810716 0.69913849 0.73014688 0.14915803 0.88659894]
 [0.76798212 0.32934119 0.04403598 0.81397568 0.71429562]
 [0.60330224 0.73290446 0.76058668 0.349051   0.14355412]
 [0.25601432 0.86070987 0.75218631 0.81613484 0.07514359]
 [0.5904549  0.21306065 0.48184404 0.72269196 0.5966606 ]]


In [38]:
myArray8=np.random.randint(10, size=(5,5))
print(myArray8)

[[5 3 0 2 9]
 [9 1 7 6 0]
 [4 0 4 4 4]
 [6 2 2 8 6]
 [8 9 0 3 6]]


In [36]:
myMatrix=myArray8[:2,:2]
print(myMatrix)

[[9 3]
 [9 9]]


In [45]:
myArray8[2,2]=100
print(myArray8)

[[  5   3   0   2   9]
 [  9   1   7   6   0]
 [  4   0 100   4   4]
 [  6   2   2   8   6]
 [  8   9   0   3   6]]


In [55]:
print(myArray8[:,2].shape)

(5,)


In [75]:
myMatrix=myArray8[1:4,1:4]
print(myMatrix)

[[  1   7   6]
 [  0 100   4]
 [  2   2   8]]
